FROM python:3.7.13-slim-buster

COPY .wgetrc .wgetrc

RUN apt-get update

RUN mkdir -p /app
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt


ADD database_scripts database_scripts 
WORKDIR /app/database_scripts

EXPOSE 8080
CMD [ "python3", "main.py"]

